### ISSUE TITLE
Consider moving this to eslint-plugin-preact

### ISSUE THREAD

**Issue by damianobarbati** [developit/eslint-config-developit#3]
Would you consider renaming/moving this to `eslint-plugin-preact`?
It's free: https://www.npmjs.com/package/eslint-plugin-preact

This would be in sync with react nomenclature `eslint-plugin-react`.

**Comment by developit** [comment]
I put a temporary package there that just provides `eslint-plugin-preact:recommended`, for now.

**Comment by developit** [comment]
All done.

**Comment by Frikki** [comment]
> I put a temporary package there that just provides eslint-plugin-preact:recommended, for now.
> All done.

I can’t seem to load it.
